// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet/greet.proto

package com.dummy.grcp.greeting.protofilesgreet;

public interface GreetDeadlineRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.GreetDeadlineRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.greet.Greeting greeting = 1;</code>
   * @return Whether the greeting field is set.
   */
  boolean hasGreeting();
  /**
   * <code>.greet.Greeting greeting = 1;</code>
   * @return The greeting.
   */
  com.dummy.grcp.greeting.protofilesgreet.Greeting getGreeting();
  /**
   * <code>.greet.Greeting greeting = 1;</code>
   */
  com.dummy.grcp.greeting.protofilesgreet.GreetingOrBuilder getGreetingOrBuilder();
}
