// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet/greet.proto

package com.dummy.grcp.greeting.protofilesgreet;

public interface TestGreetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.TestGreetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   * @return The number.
   */
  int getNumber();
}
